### PR TITLE
WIP – flat package

### PR DESCRIPTION
**Pull request by sndrs**
## What is the purpose of this change?

try to reshape the repo around the structure that will be in place when we only publish `@guardian/source` and `@guardian/editorial`

## What does this change?

-   renames `./src` to `./packages`
-   renames `./src/core` to `./packages/source`

### CODE REVIEW

**Comment by sndrs** [comment]
created #718 to ensure the chromatic tests start so that `UI Tests` check will kick in

**Comment by SiAdcock** [comment]
This looks awesome, @sndrs! What's left to do, d'you reckon?

**Comment by sndrs** [comment]
the more i've looked at it, the more i think it will be easer to leave the current stuff in place and migrate to this. the structure of `src` is quite complicated, a lot of things being imported and re-exported, i've not been able to easily update it to be one pacakge as it stands. i think a PR that manages that will be too big to review... it would be good to talk about it f2f

**Comment by sndrs** [comment]
superceded by #719

**Pull request closed without merging**
