### PR TITLE
Add logo re-export with better viewbox size

### PR DESCRIPTION
**Pull request by SiAdcock**
## What is the purpose of this change?

The logo SVG previously used very strange px values for the width and height. We should re-export using more sensible values.

## What does this change?

-   Export the Logo SVG with 300px width
-   Run logo through SVGOMG to reduce file size

### CODE REVIEW

**Comment by paperboyo** [comment]
A tad smaller (dropped precision to two decimal places):
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 97"><path d="M67.41 51.5l5.15-2.69V8.51H68.7l-9.47 12.57h-1l.55-14h40.91l.55 14h-1.1l-9.2-12.57H86v40.21l5.06 2.68v1.39H67.41zm37.52-1.85V5l-4-1.57v-.84L115.24 0h1.47v21.17l.36-.37a19.1 19.1 0 0112.24-4.62c6.25 0 9 3.51 9 10.17v23.3l3.31 1.84v1.39h-18.75v-1.39l3.4-1.84v-23.3c0-3.61-1.56-5.08-4.6-5.08a7.79 7.79 0 00-5 1.66v26.9l3.33 1.85V53h-18.74v-1.32zM153.68 36c.37 7.4 3.68 13.13 11.5 13.13 3.77 0 6.43-1.75 8.92-3.05v1.48A17.5 17.5 0 01160.3 54c-12.05 0-18.3-6.76-18.3-18.5 0-11.46 6.71-18.58 17.66-18.58 10.3 0 15.63 5.18 15.63 18.77v.37h-21.61V36zm-.19-1.66l10.67-.65c0-9.15-1.56-15.25-4.69-15.25-3.31-.04-5.98 6.98-5.98 15.86zM0 70.63c0-19.42 12.78-26.35 27-26.35 6.07 0 11.77 1 15 2.31l.28 13.59h-1.36l-8.36-13.13a12.08 12.08 0 00-5.34-.83c-7.54 0-11.49 8.79-11.31 23.21C16.09 86.72 19 94.57 26 94.57a9.36 9.36 0 004.14-.74V75.34l-4.6-2.68v-1.48h22.28v1.67l-4.59 2.49v18.22a49.32 49.32 0 01-16.74 2.86C10.3 96.51 0 88.93 0 70.63zm47.55-9.06v-1.11l15-2.59 1.65.09v29.59c0 3.6 1.75 4.62 4.6 4.62a6.31 6.31 0 004.88-2.31V63.42l-4-1.76v-1.2l14.9-2.68 1.47.09V91.8L90 93.46v1.11l-14.68 1.85-1.47-.09v-4.44h-.37a16.71 16.71 0 01-11.22 4.72c-7.17 0-10.39-4.26-10.39-10.73V63.42l-4.32-1.85zM143 57.78l1.2.09v10.91h.36c1.57-8 5.16-11 9.39-11a5 5 0 011.83.28v11.27a13.89 13.89 0 00-3-.27 18.42 18.42 0 00-8.09 1.66v21.64l3.4 1.84v1.39h-19.33V94.2l3.49-1.94V62.77l-4.05-1.2v-1l14.8-2.79z"/><path d="M180.44 58.7V47.15l-4-1.48v-.93L191.48 42l1.47.18v49.53l4.14 1.48v1.29l-14.9 2-1.2-.09v-4.04h-.36a13.09 13.09 0 01-9.84 4.16c-8.1 0-14.08-6.19-14.08-19 0-13.4 6.9-20.06 17.29-20.06a14 14 0 016.44 1.25zm0 31.71V60.83a5.28 5.28 0 00-4.14-1.29c-4 .18-6.53 6.28-6.53 17.19 0 9.8 1.75 15.26 7.18 15.07a5.28 5.28 0 003.49-1.39zm33.11-32.63l1.29.09v34.39l3.4 1.85v1.39h-19.31v-1.39l3.49-1.94V63.33l-4.14-1.67v-1.11l15.27-2.77zm1.38-9.34a6.5 6.5 0 01-6.62 6.38 6.36 6.36 0 01-6.53-6.38 6.43 6.43 0 016.53-6.44 6.57 6.57 0 016.62 6.47zm46.81 43.82V63l-4-1.48v-1.43l14.89-2.77 1.48.09v4.35h.36A19.67 19.67 0 01287.12 57c6.44 0 9.39 3.05 9.39 9.89v25.19L300 94v1.39h-19.31V94l3.49-1.94v-24.3c0-3.79-1.65-5.27-4.69-5.27a8 8 0 00-5.15 1.67v28.2l3.4 1.94v1.38h-19.31V94.3zm-21.43-18.39V69c0-7.4-1.56-9.8-6.16-9.8-.55 0-1 .09-1.56.09l-8.1 11h-1.1v-10.2A42.73 42.73 0 01237 57.78c9.93 0 15.64 2.77 15.64 11.09v23.95l3.58.92v.93a15.62 15.62 0 01-7.22 1.66c-4.88 0-7.27-1.57-8.28-4.34h-.37c-2.11 2.86-5.06 4.43-9.65 4.43-5.89 0-9.94-3.69-9.94-10.07 0-6.2 3.77-9.53 11.59-11l8-1.48zm0 16.54V75.62l-2.48.19c-3.86.37-5.34 2.86-5.34 8.32 0 6 1.94 7.58 4.7 7.58a3.65 3.65 0 003.12-1.3zM110.73 73.87V69c0-7.4-1.56-9.8-6.16-9.8-.55 0-1 .09-1.57.09l-8.09 11h-1.1v-10.2a42.63 42.63 0 0113.61-2.31c9.93 0 15.63 2.77 15.63 11.09v23.95l3.59.92v.93a15.63 15.63 0 01-7.27 1.66c-4.87 0-7.26-1.57-8.27-4.34h-.37c-2.12 2.86-5.06 4.43-9.66 4.43-5.88 0-9.93-3.69-9.93-10.07 0-6.2 3.77-9.53 11.59-11l8-1.48zm0 16.54V75.62l-2.48.19c-3.87.37-5.34 2.86-5.34 8.32 0 6 1.93 7.58 4.69 7.58a3.46 3.46 0 003.13-1.3z"/></svg>
```

**Comment by SiAdcock** [comment]
Thanks @paperboyo 💎 ! Can I ask how you achieved this? I'll probably need to do it again as I've made a change to the original.

**Comment by paperboyo** [comment]
Change to viewbox? It’s there (I used the code from this PR). If another change: I dropped precision in Illustrator (trust it more than svgomg) and then re-svgomged it. TBH, it’s still to weighty, but I didn’t wanna recreate it from scratch. Also, nobody knows, we have three distinct designs: bigger (yours) and two for smaller uses (with looser kerning), but let’s not go there, I suppose.

**Comment by SiAdcock** [comment]
@paperboyo 

> If another change

Sadly yes, we made another change to the viewbox and shifted the paths down 3px to sit at the base of the viewbox. Would you be able to do your magic again and do the same for the Guardian Live logo also on this PR? 🙏 

> two for smaller uses (with looser kerning), but let’s not go there,

Whoa! Please can we go there? I understand looser kerning to mean the letters are spaced more widely, is that correct? Where can we find these additional logos? And are there any guidelines we can formalise on when you should use a particular version of the logo? e.g. if the logo width is > 300px use the large one, else use the the smaller one?

**Comment by paperboyo** [comment]
> Please can we go there?

Why do I open me mouth?! ;-) OK. This is a question for Mr. Breuer or Mr. Clarke or Mr. Longden. I can only say, your version is what I can see on the server as `guardian_titlepiece_528pt_wide` (186mm). There are also a middle one `guardian_titlepiece_324pt_wide` (114mm) that is not much different and used nowhere AFAIK. And smallest: `guardian_titlepiece_160pt_wide` (56mm). These (print) dimensions make little sense on screens (also, HiDPI will be much, much clearer). If you really wanna go there, I would consult with one of them, and maybe use what you have everywhere and use the smallest one where the titlepiece us used tiny (anywhere?).

For your information (because I guess they do not contain any of your changes), here are both exported from Illustrator at precision `2` and then SVGOMGed (bigger one at precision `1`, cos the differences were imperceptible).

[Titlepieces.zip](https://github.com/guardian/source/files/4897727/Titlepieces.zip)

I will give you yours in a tick…

**Pull request merged**
