### PR TITLE
remove vscode settings from source control

### PR DESCRIPTION
**Pull request by sndrs**
## What is the purpose of this change?

to enable personalised setup of vscode

## What does this change?

- removes vscode settings from source control

### CODE REVIEW

**Comment by SiAdcock** [comment]
Out of interest are you finding these settings difficult to work with, or is it more like you don't believe the project should dictate settings?

**Comment by sndrs** [comment]
yeah i found the `"files.autoSave": "onFocusChange",` setting v confusing at first, had no idea what was going on :)

it was at the point i thought if you found that useful, you should be able to use it, and i should be able to disable it. only way i could think of was to remove that file from source control?

**Review by SiAdcock — DISMISSED** [review]
👍  Settings freedom for all!

**Review by SiAdcock — APPROVED** [review]

**Comment by sndrs** [comment]
interesting... https://github.com/guardian/frontend/blame/842026bc09aa6b86d9786f3484adc71f8108379a/.gitignore#L86

**Pull request merged**
