### PR TITLE
feat: change text colour of input with error to be neutral.7

### PR DESCRIPTION
**Pull request by ob6160**
## What is the purpose of this change?
After checking internally with design & ux I'm making this change to the input error text so that it's `neutral.7` instead of `error.400`

## Before
Screenshot 2021-11-04 at 12 03 05

## After
Screenshot 2021-11-04 at 12 01 19

### CODE REVIEW

**Comment by ob6160** [comment]
[Design details to check with Akemi](https://trello.com/c/nMbLPIdG/3534-design-details-to-check-with-akemi)

**Review by SiAdcock — APPROVED** [review]
Thanks so much @ob6160, this looks great 💎

**Comment by SiAdcock** [comment]
Quick Q: do we want to also apply this to select and textarea themes?

**Comment by ob6160** [comment]
> Quick Q: do we want to also apply this to [select](https://github.com/guardian/source/blob/main/packages/%40guardian/src-foundations/src/themes/select.ts) and [textarea](https://github.com/guardian/source/blob/c5103cdbe398fcaf41baf939f0740c9ad0baffd5/packages/%40guardian/src-text-area/styles.ts#L10) themes?

good Q! I'll ask Dom and get back to you

**Pull request merged**
