### PR TITLE
Sort package.jsons

### PR DESCRIPTION
**Pull request by sndrs**
## What is the purpose of this change?

make it easier to skim `package.json`s in the repo

## What does this change?

- adds `sort-package-json`
- uses it in `yarn fix`

### CODE REVIEW

**Review by jamie-lynch — APPROVED** [review]
This is nice! +1 for consistency

**Comment by SiAdcock** [comment]
This is so cool! Do we want to run it with the [`--check` flag](https://github.com/keithamus/sort-package-json#--check-flag) as part of the [`validate` script](https://github.com/guardian/source/blob/00101a428e81496794b014172ed47fb3da260482/package.json#L13)?

**Comment by sndrs** [comment]
updated to use `husky`/`lint-staged` instead. 

prob good to add a few things in here as we go, but should keep `package.json`s aligned without making noise for devs for now

**Review by SiAdcock — APPROVED** [review]
Let's do it! 👍

**Pull request merged**
