### PR TITLE
Add a 'Numeric Input' component to Source dev kitchen

### PR DESCRIPTION
**Pull request by i-hardy**
## What is the purpose of this change?

This adds a component for numeric input such as currency, with an optional prefix and suffix, based on [guidance from the GOV.UK design system](https://design-system.service.gov.uk/components/text-input/#numbers). It enforces `inputmode="numeric"`, but does not specify the input type. Its initial intended use is for checkouts on the support site, as currently we are supporting a currency prefix via awkward back-construction on top of the existing `TextInput` component:

Screenshot 2022-10-11 at 15 47 35

As the component is broadly very similar to the existing `TextInput` component I've simply copied and pasted a certain amount of things that are not currently explicitly exported from `@guardian/source-react-components`. In the future, if this component is promoted into Source proper, a lot of this code could instead be shared.

## What does this change?

- Add `NumericInput` component

## Screenshots

Screenshot 2022-10-10 at 15 59 45

Screenshot 2022-10-11 at 15 56 23

### Accessibility

- [x] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
- [x] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
- [x] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
- [x] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

### Cross browser and device testing

- [x] Tested with touch screen device

### Responsiveness

- [x] Tested at all breakpoints
- [x] Tested with with long text
- [x] Stretched to fill a wide container

### Documentation

- [x] Full API surface area is documented in the README
- [x] Examples in Storybook

### CODE REVIEW

**Comment by i-hardy** [comment]
[V2 checkout - Build 'numeric input' component in Source Development Kitchen](https://trello.com/c/YG1R9pKG/644-v2-checkout-build-numeric-input-component-in-source-development-kitchen)

**Comment by akemitakagi** [comment]
This is really nice!

**Review by joecowton1 — APPROVED** [review]
Looks great, thanks Imogen

**Comment by sndrs** [comment]
this went out in `@guardian/eslint-plugin-source-foundations@7.0.0`

**Pull request merged**
